# Generated by Django 4.2.15 on 2024-08-14 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('text', models.TextField(verbose_name='Log')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Added')),
                ('identificator', models.TextField(verbose_name='Identificator')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Message')),
                ('source_ip', models.TextField(verbose_name='Source IP')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
