# Generated by Django 4.2.15 on 2024-08-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='source_ip',
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(null=True, verbose_name='Message'),
        ),
    ]
