# Generated by Django 4.2.15 on 2024-08-17 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_remove_message_source_ip_alter_message_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='source_ip',
            field=models.TextField(default='Unknown', verbose_name='Source IP'),
        ),
        migrations.AlterField(
            model_name='message',
            name='message',
            field=models.TextField(null=True),
        ),
    ]
