# Generated by Django 4.2.15 on 2024-08-17 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0003_message_source_ip_alter_message_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='source_ip',
        ),
    ]
