# Generated by Django 4.2.15 on 2024-08-17 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0004_remove_message_source_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='source_ip',
            field=models.TextField(default='Unknown', verbose_name='Source IP'),
        ),
    ]
