# Generated by Django 4.2.15 on 2024-08-18 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0005_message_source_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='link',
            field=models.TextField(default='old', null=True),
        ),
    ]
